export const USER_NOT_FOUND = 'USER.NOT_FOUND';
export const USER_PHONE_EXIST = 'USER.PHONE_EXIST';
export const USER_ACCOUNT_EXIST = 'USER.ACCOUNT_EXIST';
export const USER_NICKNAME_EXIST = 'USER.NICKNAME_EXIST';

export const USER_PASSWORD_INVALID = 'USER.PASSWORD_INVALID';
export const USER_CERTIFICATION_CODE_INVALID =
  'USER.CERTIFICATION_CODE_INVALID';
