export const CERTIFICATION_LIMIT_EXCEEDED = 'CERTIFICATION.LIMIT_EXCEEDEDED';
export const CERTIFICATION_EXIST_CODE = 'CERTIFICATION.INVALID_CODE';
export const CERTIFICATION_CODE_NOT_FOUND = 'CERTIFICATION.NOT_FOUND';
export const CERTIFICATION_CODE_EXPIRED = 'CERTIFICATION.EXPIRED';
export const CERTIFICATION_CODE_NOT_VERIFIED = 'CERTIFICATION.NOT_VERIFIED';
export const CERTIFICATION_CODE_ALREADY_VERIFIED =
  'CERTIFICATION.ALREADY_VERIFIED';
