export const AUTH_ACCOUNT_INVALID = 'AUTH_ACCOUNT_INVALID';
export const AUTH_PASSWORD_INVALID = 'AUTH_PASSWORD_INVALID';
export const AUTH_ACCOUNT_NOT_FOUND = 'AUTH_ACCOUNT_NOT_FOUND';
export const AUTH_JWT_FAIL = 'AUTH_JWT_FAIL';
export const AUTH_JWT_INVALID = 'AUTH_JWT_INVALID';
